ishop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r"^admin/admin_update_quantities/$",
        views.adminUploadQuantities, name="adminUploadQuantities"),
    url(r"^accounts?/login/$", views.LoginView.as_view(),
        name="account_login"),
    url(r"^accounts?/signup/$", views.SignupView.as_view(),
        name="account_signup"),
    url(r"^accounts?/password_change", auth_views.PasswordChangeView.as_view(
        template_name='account/password_change.html'),
        name="password_change"),
    url(r"^password_change_done", auth_views.PasswordChangeView.as_view(
        template_name='account/password_change_done.html'),
        name="password_change_done"),
    url(r"^accounts?/", include("account.urls")),

    url(r'^$', views.itemList, name='itemlist'),

    url(r'^getitems$', views.getItems, name='getItems'),
    url(r'^getitemarray$', views.getItemArray, name='getItemArray'),
    url(r'^addtocart$', views.addToCart, name='addToCart'),
    url(r'^setincart$', views.setInCart, name='setInCart'),
    url(r'^getitemprices$', views.getItemPrices, name='getItemPrices'),
    url(r'^getcartsum$', views.getCartSum, name='getCartSum'),
    url(r'^getcart$', views.getCart, name='getCart'),
    url(r'^getinvoicepdf$', views.getInvoicePdf, name='getInvoicePdf'),
    url(r'^invoice/$', views.getInvoicePdf, name='getInvoicePdf'),
    url(r'^getinvoice', views.getInvoice, name='getInvoice'),
    url(r'^getdelivery', views.getDelivery, name='getDelivery'),
    url(r'^gettotal', views.getTotal, name='getTotal'),
    url(r'^getminordersum', views.getMinOrderSum, name='getMinOrderSum'),

    url(r'^endoforder/', views.endOfOrder, name='endOfOrder'),
    url(r'^myorders/', views.orderList, name='orderList'),

    url(r'^cart/$', views.cart, name='cart'),
    url(r'^item/(?P<itemSlug>\w+)', views.itemPage, name='item'),
    url(r'^itemlist/$', views.itemList, name='itemlist'),
    url(r'^itemlist/(?P<cls>\w+)', views.itemListSelection,
        name='itemlistselection'),
    url(r'^login/$',  RedirectView.as_view(pattern_name='account/login')),

    url(r'^order/$', views.makeOrder, name='order'),
    url(r'^about/$', views.about, name='about')
]

shop/models.py
from decimal import *
from functools import reduce
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
import xlrd


class ProductClass(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField(default='', blank=True)
    priority = models.IntegerField(default=0, blank=True)
    available = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'ProductClass'
        verbose_name_plural = 'ProductClasses'
        ordering = ['priority', 'name']

    def __str__(self):
        return str(self.name) + '(' + str(self.slug) + ')'


class Product(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    image = models.ImageField(default="nophoto.png", blank=True)
    description = models.TextField(default='', blank=True)
    priority = models.IntegerField(default=0, blank=True)
    productClass = models.ManyToManyField('ProductClass', blank=True)
    measure = models.CharField(max_length=50, default='шт', blank=True)
    available = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ['priority', 'name']

    def __str__(self):
        return str(self.name) + '(' + str(self.slug) + ')'


class ProductVariant(models.Model):
    name = models.CharField(max_length=100)
    addition = models.CharField(default='', max_length=140)
    slug = models.SlugField(unique=True)
    description = models.TextField(default='', blank=True)
    priority = models.IntegerField(default=0, blank=True)
    image = models.ImageField(default="nophoto.png", blank=True)
    product = models.ForeignKey(
        'Product', on_delete=models.CASCADE, blank=True)
    quantity = models.IntegerField(default=0, blank=True)
    vendorCode = models.CharField(default=0, max_length=50, blank=True)
    multiplicity = models.IntegerField(default=1)
    available = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'ProductVariant'
        verbose_name_plural = 'ProductVariants'
        ordering = ['priority', 'name']

    def __str__(self):
        return str(self.name) + '(' + str(self.slug) + ')'

    def getPrice(self, count):
        mn = 0
        mnCount = -1
        for price in self.price_set.all():
            if price.quantity > mnCount and price.quantity <= count:
                mn = price.price
                mnCount = price.quantity
        return mn


def updateQuantitiesXls(filename):
    startProducts = 6
    wb = xlrd.open_workbook(filename)
    sheet = wb.sheets()[0]

    updatedItems = []
    errors = []

    for rn in range(startProducts, sheet.nrows - 1):
        row = sheet.row_values(rn)
        cur_vendorCode = str(row[2])
        cur_quantity = int(row[3])

        try:
            product = ProductVariant.objects.get(vendorCode=cur_vendorCode)
            product.quantity = cur_quantity
            for invoice in Invoice.objects.filter(order__status=OrderStatus.objects.get(pk=2)):
                print(invoice.pk)

                itemInInvoice = invoice.order.items.filter(
                    product__pk=product.pk)

                if len(itemInInvoice) == 0:
                    continue

                product.quantity -= itemInInvoice[0].quantity

            product.save()
            updatedItems.append({
                                'vendorCode': product.vendorCode,
                                'name_in_file': str(row[0]),
                                'name_in_db': product.name,
                                'new_quantity': product.quantity,
                                'quantity_in_file': cur_quantity,
                                })
        except Exception as exc:
            print(exc)
            errors.append({
                'vendorCode': cur_vendorCode,
                'name_in_file': str(row[0])
            })
    return updatedItems, errors


class CarouselImage(models.Model):
    description = models.TextField(default='', blank=True)
    image = models.ImageField(default="nophoto.png", blank=True)
    product = models.ForeignKey(
        'Product', on_delete=models.CASCADE, blank=True)


class Price(models.Model):
    price = models.DecimalField(
        max_digits=50, decimal_places=2, default=0, blank=True)
    quantity = models.IntegerField(default=0, blank=True)
    productVar = models.ForeignKey(
        'ProductVariant', on_delete=models.CASCADE, default=0, blank=True)

    class Meta:
        verbose_name = 'Price'
        verbose_name_plural = 'Prices'
        ordering = ['productVar', 'quantity']

    def __str__(self):
        return 'Price:' + str(self.productVar.name) + " : " + \
            str(self.quantity) + " : " + str(self.price)


class SaleSum(models.Model):
    name = models.CharField(max_length=140)
    sale = models.DecimalField(
        max_digits=50, decimal_places=2, default=0, blank=True)
    productClasses = models.ManyToManyField('ProductClass', blank=True)
    startSum = models.DecimalField(
        max_digits=50, decimal_places=2, default=0, blank=True)
    customers = models.ManyToManyField('auth.Group', blank=True)

    class Meta:
        verbose_name = 'SaleSum'
        verbose_name_plural = 'SalesSum'
        ordering = ['sale', 'name']

    def __str__(self):
        return 'SSale:' + str(self.name) + '(' + str(self.sale) + ')'

    def forUser(self, user):
        return any(
            map(
                (lambda x: user in x.user_set.all()),
                self.customers.all()
            )
        )

    def forProduct(self, product):
        return len(product.product.productclass_set.all().intersect()) != 0

    def checkOrder(self, order):
        if not self.forUser(order.user):
            return False
        sm = reduce(
            (lambda a, b: a + b),
            map(
                (lambda item: Decimal(item.price) * Decimal(item.quantity)),
                order.items.objects.all()
            )
        )

        return sm >= startSum


class SaleQuantity(models.Model):
    name = models.CharField(max_length=140)
    sale = models.DecimalField(
        max_digits=50, decimal_places=2, default=0, blank=True)
    productClasses = models.ManyToManyField('ProductClass', blank=True)
    startQuantity = models.IntegerField(default=0, blank=True)
    customers = models.ManyToManyField('auth.Group', blank=True)

    class Meta:
        verbose_name = 'SaleQuantity'
        verbose_name_plural = 'SalesQuantity'
        ordering = ['sale', 'name']

    def __str__(self):
        return 'QSale:' + str(self.name) + '(' + str(self.sale) + ')'

    def checkOrder(self, order):
        if not forUser(order.user):
            return False
        sm = reduce(
            (lambda a, b: a + b),
            map(
                (lambda item: item.quantity),
                order.items.objects.all()
            )
        )
        return sm >= startQuantity


class Organisation(models.Model):
    inn = models.CharField(max_length=20, default='', blank=True)
    kpp = models.CharField(max_length=20, default='', blank=True)
    address = models.CharField(max_length=250, default='', blank=True)
    name = models.CharField(max_length=250, default='', blank=True)
    owners = models.ManyToManyField('auth.User', blank=True)

    class Meta:
        verbose_name = 'Organisation'
        verbose_name_plural = 'Organisations'
        ordering = ['inn']

    def __str__(self):
        return str(self.name) + '(' + str(self.inn) + ')'


class SellerOrganisation(models.Model):
    inn = models.CharField(max_length=20, default='', blank=True)
    kpp = models.CharField(max_length=20, default='', blank=True)
    address = models.CharField(max_length=250, default='', blank=True)
    name = models.CharField(max_length=250, default='', blank=True)
    owners = models.ManyToManyField('auth.User', blank=True)
    bik = models.CharField(max_length=50, default='', blank=True)
    corAcc = models.CharField(max_length=250, default='', blank=True)
    bank = models.CharField(max_length=250, default='', blank=True)
    checkACC = models.CharField(max_length=50, default='', blank=True)

    class Meta:
        verbose_name = 'SellerOrganisation'
        verbose_name_plural = 'SellerOrganisations'
        ordering = ['inn']

    def __str__(self):
        return 'Seller: ' + str(self.name) + '(' + str(self.inn) + ')'


class OrderItem(models.Model):
    product = models.ForeignKey(
        'ProductVariant', on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, blank=True)
    price = models.DecimalField(
        max_digits=50,
        decimal_places=2,
        default=0,
        blank=True
    )  # price per one
    order = models.ForeignKey('Order',
                              on_delete=models.SET_NULL,
                              related_name='items',
                              related_query_name='items',
                              blank=True,
                              null=True)

    class Meta:
        verbose_name = 'OrderItem'
        verbose_name_plural = 'OrderItems'
        # ordering = ['product']

    def __str__(self):
        return 'OrderItem:' + str(self.product) + ' ' + str(self.quantity)

    def getSum(self):
        # print(Decimal(self.price), int(self.quantity))
        return Decimal(self.price) * int(self.quantity)


class OrderStatus(models.Model):
    name = models.CharField(max_length=250, default='', blank=True)
    color = models.CharField(max_length=200, default='', blank=True)

    class Meta:
        verbose_name = 'OrderStatus'
        verbose_name_plural = 'OrderStatuses'
        ordering = ['name']

    def __str__(self):
        return self.name + ' (' + self.color + ')'


class Order(models.Model):
    datetime = models.DateTimeField(null=True, blank=True)

shop/forms.py
import account.forms
from django import forms


class SignupForm(account.forms.SignupForm):

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        del self.fields["username"]


class UploadFileForm(forms.Form):
    file = forms.FileField()

templates/shop/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load l10n %}

{% block head %}
<script>
$(document).ready(function() {
    $("#nav_about").attr("class", "active");
});
</script>
{% endblock %}

{% block content %}
<a name="about"></a>
<h1>
    Shop name
</h1>
<div class="row">
    <h3>О Магазине</h3>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id velit vitae velit tempus dictum. Donec condimentum non quam a sagittis. Nulla efficitur magna felis, nec tempus purus venenatis ultrices. Cras condimentum tincidunt sem in commodo. Duis venenatis sapien ac odio posuere lacinia. Etiam sed elit feugiat, ornare ipsum vitae, elementum lectus. Proin eleifend nec orci ut vestibulum. Curabitur viverra mi velit, id convallis ipsum viverra non. Fusce ut egestas purus. Curabitur dolor magna, vehicula eu urna eu, faucibus vehicula erat.
    </p>
    <p>
    Aliquam sagittis congue tincidunt. Mauris gravida sem vitae ex facilisis feugiat. Curabitur tempus faucibus arcu eu luctus. Quisque condimentum iaculis tortor, id semper neque tincidunt vitae. Nam sed mattis magna, eu maximus tortor. Praesent ligula nulla, cursus vitae facilisis eu, laoreet eget sapien. Integer et laoreet justo. Integer sit amet massa sed nunc vulputate hendrerit. Morbi malesuada, augue eu cursus sagittis, justo mi iaculis justo, a laoreet felis ipsum ac neque. Curabitur auctor, lacus vitae tempus gravida, tortor nulla pretium nisl, sit amet fringilla enim ante et dui. Nulla tincidunt auctor egestas. Suspendisse potenti. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vitae suscipit dui, nec tristique est. Pellentesque at urna tellus.
    </p>
    <p>
    Curabitur interdum faucibus nibh sit amet semper. Duis pharetra lacinia dui sit amet pellentesque. Praesent dui justo, pulvinar ac ante mattis, rhoncus lobortis dui. Vivamus in lectus at elit eleifend tristique sed eget dui. Etiam eu viverra nunc. Donec a fermentum mauris. Mauris in ullamcorper arcu. Donec sit amet rhoncus lorem. Nulla fermentum lorem ac massa posuere venenatis. Nam imperdiet posuere velit, sed facilisis lacus imperdiet ut. Nulla sit amet urna quis leo efficitur lobortis ac eu diam. Ut a elementum orci. Suspendisse tempor vitae massa in imperdiet. Sed ullamcorper tellus ut feugiat finibus.
    </p>
    <p>
    Cras ut ligula ut dolor sollicitudin convallis non et arcu. Aliquam erat volutpat. Nunc tempor sagittis tincidunt. Pellentesque in nibh ex. Nulla sed justo nisi. Donec consequat molestie nulla et euismod. Mauris auctor dapibus congue.
    </p>
    <p>
    Suspendisse neque felis, ullamcorper sed ligula at, tempus commodo enim. Ut suscipit, sapien eget dapibus elementum, magna elit pretium turpis, vel sagittis nibh turpis congue mi. Vestibulum pretium venenatis nulla, a pellentesque enim lacinia ut. Nunc id dignissim erat. Ut eget odio euismod nisl posuere consequat a at turpis. Etiam sed enim at ex molestie molestie. Proin molestie consequat orci, in vehicula dui vulputate vitae. Suspendisse accumsan sagittis nulla ac porttitor. Nulla eget pharetra erat. Cras ipsum tellus, pretium ac sem sit amet, efficitur faucibus turpis. Pellentesque faucibus ipsum arcu. Etiam aliquet lacinia felis ac ultricies.
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id velit vitae velit tempus dictum. Donec condimentum non quam a sagittis. Nulla efficitur magna felis, nec tempus purus venenatis ultrices. Cras condimentum tincidunt sem in commodo. Duis venenatis sapien ac odio posuere lacinia. Etiam sed elit feugiat, ornare ipsum vitae, elementum lectus. Proin eleifend nec orci ut vestibulum. Curabitur viverra mi velit, id convallis ipsum viverra non. Fusce ut egestas purus. Curabitur dolor magna, vehicula eu urna eu, faucibus vehicula erat.
    </p>
    <p>
    Aliquam sagittis congue tincidunt. Mauris gravida sem vitae ex facilisis feugiat. Curabitur tempus faucibus arcu eu luctus. Quisque condimentum iaculis tortor, id semper neque tincidunt vitae. Nam sed mattis magna, eu maximus tortor. Praesent ligula nulla, cursus vitae facilisis eu, laoreet eget sapien. Integer et laoreet justo. Integer sit amet massa sed nunc vulputate hendrerit. Morbi malesuada, augue eu cursus sagittis, justo mi iaculis justo, a laoreet felis ipsum ac neque. Curabitur auctor, lacus vitae tempus gravida, tortor nulla pretium nisl, sit amet fringilla enim ante et dui. Nulla tincidunt auctor egestas. Suspendisse potenti. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vitae suscipit dui, nec tristique est. Pellentesque at urna tellus.
    </p>
    <p>
    Curabitur interdum faucibus nibh sit amet semper. Duis pharetra lacinia dui sit amet pellentesque. Praesent dui justo, pulvinar ac ante mattis, rhoncus lobortis dui. Vivamus in lectus at elit eleifend tristique sed eget dui. Etiam eu viverra nunc. Donec a fermentum mauris. Mauris in ullamcorper arcu. Donec sit amet rhoncus lorem. Nulla fermentum lorem ac massa posuere venenatis. Nam imperdiet posuere velit, sed facilisis lacus imperdiet ut. Nulla sit amet urna quis leo efficitur lobortis ac eu diam. Ut a elementum orci. Suspendisse tempor vitae massa in imperdiet. Sed ullamcorper tellus ut feugiat finibus.
    </p>
    <p>
    Cras ut ligula ut dolor sollicitudin convallis non et arcu. Aliquam erat volutpat. Nunc tempor sagittis tincidunt. Pellentesque in nibh ex. Nulla sed justo nisi. Donec consequat molestie nulla et euismod. Mauris auctor dapibus congue.
    </p>
    <p>
    Suspendisse neque felis, ullamcorper sed ligula at, tempus commodo enim. Ut suscipit, sapien eget dapibus elementum, magna elit pretium turpis, vel sagittis nibh turpis congue mi. Vestibulum pretium venenatis nulla, a pellentesque enim lacinia ut. Nunc id dignissim erat. Ut eget odio euismod nisl posuere consequat a at turpis. Etiam sed enim at ex molestie molestie. Proin molestie consequat orci, in vehicula dui vulputate vitae. Suspendisse accumsan sagittis nulla ac porttitor. Nulla eget pharetra erat. Cras ipsum tellus, pretium ac sem sit amet, efficitur faucibus turpis. Pellentesque faucibus ipsum arcu. Etiam aliquet lacinia felis ac ultricies.
    </p>
    <a name="contacts"></a>
    <h3>Контакты</h3>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id velit vitae velit tempus dictum. Donec condimentum non quam a sagittis. Nulla efficitur magna felis, nec tempus purus venenatis ultrices. Cras condimentum tincidunt sem in commodo. Duis venenatis sapien ac odio posuere lacinia. Etiam sed elit feugiat, ornare ipsum vitae, elementum lectus. Proin eleifend nec orci ut vestibulum. Curabitur viverra mi velit, id convallis ipsum viverra non. Fusce ut egestas purus. Curabitur dolor magna, vehicula eu urna eu, faucibus vehicula erat.
    </p>
    <p>
    Aliquam sagittis congue tincidunt. Mauris gravida sem vitae ex facilisis feugiat. Curabitur tempus faucibus arcu eu luctus. Quisque condimentum iaculis tortor, id semper neque tincidunt vitae. Nam sed mattis magna, eu maximus tortor. Praesent ligula nulla, cursus vitae facilisis eu, laoreet eget sapien. Integer et laoreet justo. Integer sit amet massa sed nunc vulputate hendrerit. Morbi malesuada, augue eu cursus sagittis, justo mi iaculis justo, a laoreet felis ipsum ac neque. Curabitur auctor, lacus vitae tempus gravida, tortor nulla pretium nisl, sit amet fringilla enim ante et dui. Nulla tincidunt auctor egestas. Suspendisse potenti. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vitae suscipit dui, nec tristique est. Pellentesque at urna tellus.
    </p>
    <p>
    Curabitur interdum faucibus nibh sit amet semper. Duis pharetra lacinia dui sit amet pellentesque. Praesent dui justo, pulvinar ac ante mattis, rhoncus lobortis dui. Vivamus in lectus at elit eleifend tristique sed eget dui. Etiam eu viverra nunc. Donec a fermentum mauris. Mauris in ullamcorper arcu. Donec sit amet rhoncus lorem. Nulla fermentum lorem ac massa posuere venenatis. Nam imperdiet posuere velit, sed facilisis lacus imperdiet ut. Nulla sit amet urna quis leo efficitur lobortis ac eu diam. Ut a elementum orci. Suspendisse tempor vitae massa in imperdiet. Sed ullamcorper tellus ut feugiat finibus.
    </p>
    <p>
    Cras ut ligula ut dolor sollicitudin convallis non et arcu. Aliquam erat volutpat. Nunc tempor sagittis tincidunt. Pellentesque in nibh ex. Nulla sed justo nisi. Donec consequat molestie nulla et euismod. Mauris auctor dapibus congue.
    </p>
    <p>
    Suspendisse neque felis, ullamcorper sed ligula at, tempus commodo enim. Ut suscipit, sapien eget dapibus elementum, magna elit pretium turpis, vel sagittis nibh turpis congue mi. Vestibulum pretium venenatis nulla, a pellentesque enim lacinia ut. Nunc id dignissim erat. Ut eget odio euismod nisl posuere consequat a at turpis. Etiam sed enim at ex molestie molestie. Proin molestie consequat orci, in vehicula dui vulputate vitae. Suspendisse accumsan sagittis nulla ac porttitor. Nulla eget pharetra erat. Cras ipsum tellus, pretium ac sem sit amet, efficitur faucibus turpis. Pellentesque faucibus ipsum arcu. Etiam aliquet lacinia felis ac ultricies.
    </p>
    <img width="600px" height="600px" alt="карта">
    </img>
</div>

{% endblock %}

templates/shop/endoforder.html
{% extends 'base.html' %}
{% load l10n %}

{% block head %}
<script>
$(document).ready(function() {
    $("#nav_cart").attr("class", "active");
});
</script>
{% endblock %}

{% block content %}
<div class="row">
    <h1 align="center">Заказ оформлен</h1>
</div>
<div class="row">
    {% if notification %}
        <div class="alert alert-warning">
            <h4 align="center">
                <strong>Внимание!</strong>
                <p>Не все из заказанных товаров есть в наличии на складе. С вами свяжется менеджер для обсуждения заказа.</p>
            </h4>
        </div>
    {% endif %}
    </div>
<div class="row">
<h2 align="center">
    Спасибо за заказ, вам на эл. почту выслан счет в формате pdf.
</h2>
</div>
<div class="row">
<h2 align="center">
    В случае возникновения проблем или вопросов обращайтесь по адресу <a href="mailto:email@email.com">email@email.com</a>.
</h2>
</div>
<hr/>
<div class="row">

</div>
<iframe src='/getinvoicepdf?pk={{pk}}' width="100%" height="800px"></iframe>
<!--<div class="row">
<div id="table" class="row">
    <h2>Заказ</h2>
        <table class="table table-striped">
            <thead>
              <tr>
                <th>Наименование</th>
                <th>Цена</th>
                <th>Количество</th>
                <th>Мера</th>
                <th>Сумма</th>
              </tr>
            </thead>
            <tbody>
                {% for orderItem in invoice.order.items.all %}
                    <tr id="tr_{{orderItem.pk}}">
                        <th>
                            <h5>
                        <span data-toggle="popover" title="{{ orderItem.product.name }}" data-html="true"
                            data-content="
                        <div>
                            <img class='img-circle' src='/media/{{ orderItem.product.image }}' height='100px' width='100px' />
                        </div>
                        <div>
                            {{ orderItem.product.description|safe }}
                        </div>
                        <div>
                            {% for pclass in orderItem.product.product.productClass.all %}
                                <a href='itemlist/{{pclass.slug}}' class='btn btn-primary'>{{pclass.name}}</a>
                            {% endfor%}
                        </div>">{{ orderItem.product.name }} </span>
                        </h5>
                        </th>
                        <th>
                            {{orderItem.price}} p
                        </th>
                        <th>
                            <span id="quantity_{{orderItem.pk}}">{{orderItem.quantity}}</span>
                        </th>
                        <th>
                            {{orderItem.product.product.measure}}
                        </th>
                        <th>
                            <span id="sm_{{orderItem.pk}}"> {{ orderItem.getSum }}</span> p
                        </th>
                    </tr>
                {% endfor %}
                 <tr>
                    <th>Скидка:</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th> {{invoice.order.sale}} р</th>
                </tr>
                <tr>
                    <th>Итог:</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>{{invoice.order.getTotalSum}} р</th>
                </tr>
            <tbody/>
        </table>
    </div>
</div>-->

{% endblock %}

templates/shop/itemPage.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block content %}
<div>
    <h3>{{ item.name }}</h3>
    <img src="/media/{{ item.image }}" height="100px" width="100px" />
</div>
<div>
   <p> {{ item.description|safe }}</p>
</div>
<div>
   <h5>относится к</h5>
   <ul>
    {% for pclass in item.productClass.all %}
        <li>{{pclass.name}}</li>
    {% endfor%}
   </ul>
</div>
<div>
    <h5>варианты</h5>
    <ul>
        {% for pvar in item.productvariant_set.all %}
            <li>
                <div>
                    {{pvar.name}}
                </div>
                <div>
                    {{pvar.addition}}
                </div>
                <div>
                    цена: {{pvar.price}}
                </div>
            </li>
        {% endfor%}
    </ul>
</div>
{% endblock %}

templates/shop/orderlist.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load l10n %}

{% block head %}
<script>
$(document).ready(function() {
    $("#nav_myorders").attr("class", "active");
});
</script>
{% endblock %}

{% block content %}
<h1>
    Заказы
</h1>
<div class="row">
    <table class="table table-striped">
        <tr>
            <th>Счет&nbsp;№</th>
            <th>Дата</th>
            <th>Состояние</th>
            <th>Трек номер</th>
            <th>Покупатель</th>
            <th>Продавец</th>
            <th>Сумма</th>
            <th><th>
        </tr>
        {% for invoice in invoices %}
        <tr>
            <td>
                {{invoice.pk}}
            </td>
            <td>
                {{invoice.date|date:"DATE_FORMAT"}}
            </td>
            <td>
                <strong>
                    {% if invoice.order.status %}
                    <center>
                        <span style="color: {{invoice.order.status.color}};"> {{invoice.order.status.name}} </span>
                    </center>
                    {% endif %}
                </strogn>
            </td>
            <td>
                {% if invoice.trackNumber %}
                    <span> {{invoice.trackNumber}} </span>
                {% else %}
                    <center>
                        -
                    </center>
                {% endif %}
            </td>
            <td>
                {{invoice.customer.name}}
            </td>
            <td>
                {{invoice.seller.name}}
            </td>
            <td>
                {{invoice.toPay|floatformat:2|localize}}&nbsp;р
            </td>

            <td>
                <a type="button" class="btn btn-default" href="/getinvoicepdf?pk={{invoice.pk}}" target="_blank">
                    <span class="glyphicon glyphicon-file"></span>Скачать счет
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}